spring.application.name=Product-Service
spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=7777
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ===============================
# REDIS CONFIG
# ===============================

spring.data.redis.client-name=shopsphere-redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=100ms
spring.data.redis.connect-timeout=100ms




# ===============================
# CACHE CONFIG (Spring Cache)
# ===============================
spring.cache.type=none
spring.cache.redis.cache-null-values=false
spring.cache.redis.enable-statistics=false

# Log Spring Cache operations
logging.level.org.springframework.cache=DEBUG

# Log Redis template operations
logging.level.org.springframework.data.redis.core=DEBUG

# Optional: Log Redis connection factory operations
logging.level.org.springframework.data.redis.connection=DEBUG

# -------- YOUR CACHE CONFIG LOGS --------
logging.level.com.shopsphere.product.config=DEBUG

# -------- YOUR SERVICE LOGS --------
#logging.level.com.shopsphere.product.serviceImpl=DEBUG




